import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import Navbar from './components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider  publishableKey='pk_test_aW5ub2NlbnQtZW11LTYuY2xlcmsuYWNjb3VudHMuZGV2JA    '>

    <html lang="en">
      <body className={inter.className}>
        <header>
          <Navbar />
        </header>
        {children}

        </body>
    </html>
    </ClerkProvider>
  )
}
